
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

target 'FariasDoMesmoSaco' do

  use_frameworks!

  # Pods for FariasDoMesmoSaco

pod 'Alamofire', '~> 4.7'

pod "youtube-ios-player-helper", "~> 0.1.4"

pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'Firebase/Auth'
pod 'GoogleSignIn'

#pod "YouTube-Player-iOS-Helper", "~>0.1"

  target 'FariasDoMesmoSacoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FariasDoMesmoSacoUITests' do
    inherit! :search_paths
    # Pods for testing
  end


end
